base:
  project: sentiment-classifier
  random state: 122
  target_col: TARGET

data_source:
  s3_source: data/data_given/data.csv
load_data:
  raw_dataset_csv: data/raw/data.csv

split_data:
  train_path: data/preprocessed/train.csv
  test_path: data/preprocessed/test.csv
  test_size:0.2
estimators:
  LogisticRegression:
    params:
      penalty: l2
      class_weight: balanced
      C: 0.05
model_dir: saved_models


      

